version: '3'

services:
    web:
        image: nginx:1.13.7-alpine
        ports:
            - "8080:80"
        volumes:
            - ./:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        image: php:7.1.11-fpm-alpine
        volumes:
            - ./:/code
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
